name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build and run docker container
      run: |
         docker build -t c-server:latest .
         docker run -d -p 8000:8000 --name c-server c-server:latest
         sleep 5

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v2
      with:
         version: latest
         platform: x64
    
    - name: Install C compiler
      run: |
        sudo apt update
        sudo apt install -y build-essential


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy to aws
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          port: 8000
        with:
          script_after: |
            cd  ~/my-app
            git fetch origin
            git reset --hard origin/main
            sudo docker build -t c-server . 
            sudo docker stop $(docker ps -q) || true
            sudo docker rm $(docker ps -aq) || true
            sudo docker run -d -p 8000:8000 c-server
            
